// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfdxiyuvidsmnvevutib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZHhpeXV2aWRzbW52ZXZ1dGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzA4NDAsImV4cCI6MjA2MjI0Njg0MH0.K88wETZ6C5MXu-6UkQYVf9nSMPPQMCp_Ya5gkpap2jE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);